playoff_career_steals_leaders = {
    1: {"player": "LeBron James", "steals": 506},
    2: {"player": "Scottie Pippen", "steals": 395},
    3: {"player": "Michael Jordan", "steals": 376},
    4: {"player": "Magic Johnson", "steals": 358},
    5: {"player": "John Stockton", "steals": 338},
    6: {"player": "James Harden", "steals": 313},
    7: {"player": "Kobe Bryant", "steals": 310},
    8: {"player": "Jason Kidd", "steals": 302},
    9: {"player": "Larry Bird", "steals": 296},
    10: {"player": "Maurice Cheeks", "steals": 295},

    11: {"player": "Manu Ginóbili", "steals": 292},
    12: {"player": "Chris Paul", "steals": 287},
    13: {"player": "Julius Erving", "steals": 287},
    14: {"player": "Clyde Drexler", "steals": 278},
    15: {"player": "Robert Horry", "steals": 276},
    16: {"player": "Dwyane Wade", "steals": 273},
    17: {"player": "Derek Fisher", "steals": 272},
    18: {"player": "Karl Malone", "steals": 258},
    19: {"player": "Draymond Green", "steals": 257},
    20: {"player": "Kawhi Leonard", "steals": 256},

    21: {"player": "Dennis Johnson", "steals": 247},
    22: {"player": "Hakeem Olajuwon", "steals": 245},
    23: {"player": "Isiah Thomas", "steals": 234},
    24: {"player": "Stephen Curry", "steals": 231},
    25: {"player": "Rajon Rondo", "steals": 228},
    26: {"player": "Byron Scott", "steals": 226},
    27: {"player": "Russell Westbrook", "steals": 223},
    28: {"player": "Jimmy Butler", "steals": 217},
    29: {"player": "Andre Iguodala", "steals": 217},
    30: {"player": "Gary Payton", "steals": 216},

    31: {"player": "Paul Pierce", "steals": 204},
    32: {"player": "Michael Cooper", "steals": 203},
    33: {"player": "Ben Wallace", "steals": 199},
    34: {"player": "Tony Parker", "steals": 198},
    35: {"player": "Charles Barkley", "steals": 193},
    36: {"player": "Kareem Abdul-Jabbar", "steals": 189},
    37: {"player": "Paul George", "steals": 186},
    38: {"player": "Kevin Garnett", "steals": 178},
    39: {"player": "Charles Oakley", "steals": 178},
    40: {"player": "Danny Green", "steals": 177},

    41: {"player": "Rajon Rondo", "steals": 176},
    42: {"player": "Vlade Divac", "steals": 174},
    43: {"player": "Dennis Rodman", "steals": 172},
    44: {"player": "Shane Battier", "steals": 171},
    45: {"player": "Joe Dumars", "steals": 170},
    46: {"player": "Tayshaun Prince", "steals": 169},
    47: {"player": "Robert Parish", "steals": 168},
    48: {"player": "Derek Harper", "steals": 167},
    49: {"player": "Cliff Robinson", "steals": 166},
    50: {"player": "Jason Terry", "steals": 165}
}