"""
100 NBA facts -- a mix of well-known, obscure, and just-plain-random trivia.
category is one of: "normal", "obscure", "random"
"""

nba_facts = {
    1: {"fact": "Wilt Chamberlain scored 100 points in a single game for the Philadelphia Warriors on March 2, 1962, still the NBA's single-game scoring record.", "category": "normal"},
    2: {"fact": "Michael Jordan won all six of his NBA Finals with the Chicago Bulls and was named Finals MVP in every one of them.", "category": "normal"},
    3: {"fact": "LeBron James passed Kareem Abdul-Jabbar to become the NBA's all-time leading scorer in February 2023.", "category": "normal"},
    4: {"fact": "The NBA introduced the three-point line for the 1979-80 season.", "category": "normal"},
    5: {"fact": "The 24-second shot clock was introduced in 1954 to speed up the pace of NBA games.", "category": "normal"},
    6: {"fact": "The NBA was founded in 1946 as the Basketball Association of America (BAA) and took the NBA name in 1949 after merging with the rival National Basketball League.", "category": "normal"},
    7: {"fact": "Bill Russell won 11 NBA championships with the Boston Celtics, the most of any player in league history.", "category": "normal"},
    8: {"fact": "The Boston Celtics and Los Angeles Lakers are tied for the most NBA championships of any franchise.", "category": "normal"},
    9: {"fact": "The 1995-96 Chicago Bulls set the NBA record for regular-season wins at 72-10, a mark the 2015-16 Golden State Warriors later broke by going 73-9.", "category": "normal"},
    10: {"fact": "Kareem Abdul-Jabbar's signature shot, the skyhook, was considered nearly unblockable due to its release point and his height.", "category": "normal"},
    11: {"fact": "Kobe Bryant scored 81 points in a single game against the Toronto Raptors in 2006, the second-highest single-game total in NBA history behind Wilt Chamberlain's 100.", "category": "normal"},
    12: {"fact": "The NBA draft lottery was introduced in 1985 to discourage teams from deliberately losing games to secure better draft picks.", "category": "normal"},
    13: {"fact": "Magic Johnson and Larry Bird first faced off in the 1979 NCAA championship game before becoming NBA rivals with the Lakers and Celtics.", "category": "normal"},
    14: {"fact": "Michael Jordan was cut from his high school varsity basketball team as a sophomore.", "category": "normal"},
    15: {"fact": "Hakeem Olajuwon and Michael Jordan were teammates on the same high school-aged pickup circuit briefly before both became Hall of Famers.", "category": "obscure"},
    16: {"fact": "The Houston Rockets selected Hakeem Olajuwon first overall in the 1984 draft, ahead of Michael Jordan, who went third to the Chicago Bulls.", "category": "normal"},
    17: {"fact": "Portland selected Sam Bowie second overall in the 1984 draft, one pick ahead of Michael Jordan.", "category": "normal"},
    18: {"fact": "Manute Bol and Gheorghe Muresan share the record for tallest players in NBA history at 7 feet 7 inches.", "category": "normal"},
    19: {"fact": "Muggsy Bogues, at 5 feet 3 inches, is the shortest player ever to play in the NBA.", "category": "normal"},
    20: {"fact": "Wilt Chamberlain famously claimed he never fouled out of an NBA game in his entire career.", "category": "obscure"},
    21: {"fact": "The Sacramento Kings franchise has moved cities more times than any other NBA team, having been based in Rochester, Cincinnati, Kansas City, and Sacramento.", "category": "obscure"},
    22: {"fact": "The original Charlotte Hornets relocated to New Orleans in 2002, while a new Charlotte franchise (the Bobcats) was later renamed the Hornets in 2014.", "category": "obscure"},
    23: {"fact": "The Toronto Huskies played in the very first NBA game in 1946 and folded after just one season.", "category": "obscure"},
    24: {"fact": "The Providence Steamrollers were one of the NBA's original franchises and lasted only three seasons before folding.", "category": "obscure"},
    25: {"fact": "Wilt Chamberlain averaged 50.4 points per game for an entire season in 1961-62, a record that has never come close to being broken.", "category": "normal"},
    26: {"fact": "The 'Dream Team' at the 1992 Barcelona Olympics is widely considered the greatest collection of basketball talent ever assembled on one roster.", "category": "normal"},
    27: {"fact": "Dirk Nowitzki played his entire 21-season NBA career with the Dallas Mavericks.", "category": "normal"},
    28: {"fact": "Kobe Bryant entered the NBA draft straight out of high school and was selected 13th overall by the Charlotte Hornets before being traded to the Lakers.", "category": "normal"},
    29: {"fact": "The Golden State Warriors franchise began in Philadelphia before relocating to San Francisco and eventually Oakland, then back to San Francisco.", "category": "obscure"},
    30: {"fact": "Wilt Chamberlain and Bill Russell were fierce on-court rivals but were also close friends off the court, even sharing Thanksgiving dinners.", "category": "obscure"},
    31: {"fact": "Shaquille O'Neal was a notoriously poor free-throw shooter, career shooting around 53% from the line despite his dominance in the paint.", "category": "normal"},
    32: {"fact": "The NBA's Sixth Man of the Year Award was renamed the John Havlicek Trophy starting with the 2022-23 season.", "category": "obscure"},
    33: {"fact": "Steph Curry set the single-season three-point record with 402 made threes in the 2015-16 season, breaking his own previous record.", "category": "normal"},
    34: {"fact": "The NBA All-Star Game has been played every year since 1951 except for 1999 and 2021, when it was skipped or altered due to labor disputes and the COVID-19 pandemic.", "category": "obscure"},
    35: {"fact": "Wilt Chamberlain led the league in assists in the 1967-68 season, the only center ever to lead the NBA in assists for a season.", "category": "obscure"},
    36: {"fact": "The Utah Jazz franchise actually began as the New Orleans Jazz before relocating to Utah in 1979, which is why a team in a state famous for the Mormon religion is named after a musical genre associated with New Orleans.", "category": "random"},
    37: {"fact": "Michael Jordan briefly retired from basketball in 1993 to play minor league baseball for the Birmingham Barons.", "category": "normal"},
    38: {"fact": "The trophy given to the NBA Finals champion is named the Larry O'Brien Championship Trophy, after a former NBA commissioner.", "category": "normal"},
    39: {"fact": "The regular-season MVP trophy is named the Michael Jordan Trophy as of the 2022-23 season, replacing the previous unnamed award.", "category": "obscure"},
    40: {"fact": "Yao Ming was the first international player with no U.S. college experience to be selected first overall in the NBA draft.", "category": "normal"},
    41: {"fact": "Dennis Rodman led the NBA in rebounding for seven consecutive seasons despite being undersized for a power forward.", "category": "normal"},
    42: {"fact": "The 'Malice at the Palace' brawl between the Indiana Pacers and Detroit Pistons in 2004 spilled into the stands and led to some of the longest suspensions in NBA history.", "category": "normal"},
    43: {"fact": "Allen Iverson is one of the shortest players ever to win the NBA MVP award, standing at just 6 feet tall.", "category": "obscure"},
    44: {"fact": "The San Antonio Spurs went from the worst record in the league to drafting Tim Duncan first overall in 1997, a stretch of luck fans nicknamed 'The Duncan Fund.'", "category": "obscure"},
    45: {"fact": "David Robinson's injury in the 1996-97 season directly led to the Spurs' terrible record and their eventual drafting of Tim Duncan.", "category": "obscure"},
    46: {"fact": "The NBA experimented with a four-point line in the D-League (now G League) as a rule test that never made it to the main league.", "category": "obscure"},
    47: {"fact": "Larry Bird once scored 60 points in a game against the Atlanta Hawks despite playing with a badly injured back for much of that season.", "category": "obscure"},
    48: {"fact": "The Detroit Pistons won back-to-back championships in 1989 and 1990 with a defense-first team nicknamed the 'Bad Boys.'", "category": "normal"},
    49: {"fact": "Julius 'Dr. J' Erving popularized the slam dunk as a signature offensive weapon during his years in the ABA before it merged with the NBA.", "category": "normal"},
    50: {"fact": "The ABA-NBA merger in 1976 brought four teams into the NBA: the San Antonio Spurs, Denver Nuggets, Indiana Pacers, and New York (Brooklyn) Nets.", "category": "normal"},
    51: {"fact": "The red, white, and blue basketball used in some ABA games became a lasting visual symbol of that league's flashier style of play.", "category": "obscure"},
    52: {"fact": "Julius Erving won ABA MVP three times before ever winning an NBA title with the Philadelphia 76ers in 1983.", "category": "obscure"},
    53: {"fact": "The tradition of players wearing long shorts in the NBA is often traced back to Michael Jordan, who wanted room to wear his North Carolina shorts underneath his Bulls uniform.", "category": "random"},
    54: {"fact": "The Miami Heat's 'Big Three' era with LeBron James, Dwyane Wade, and Chris Bosh produced two NBA championships between 2010 and 2014.", "category": "normal"},
    55: {"fact": "Ray Allen hit a clutch game-tying three-pointer in Game 6 of the 2013 Finals that is widely regarded as one of the most dramatic shots in Finals history.", "category": "normal"},
    56: {"fact": "The Golden State Warriors' 'Splash Brothers' nickname refers to the shooting duo of Stephen Curry and Klay Thompson.", "category": "normal"},
    57: {"fact": "Vince Carter played 22 seasons in the NBA, the longest career in league history at the time he retired, before LeBron James eventually surpassed it.", "category": "normal"},
    58: {"fact": "Vince Carter is the only player in NBA history to play in four different decades, having debuted in 1998 and retired in 2020.", "category": "obscure"},
    59: {"fact": "The 'Dream Shake' was Hakeem Olajuwon's signature series of pivot and fake moves in the post, still studied by big men today.", "category": "normal"},
    60: {"fact": "The NBA logo, a silhouette of a player dribbling, is modeled after Hall of Famer Jerry West, though the league has never officially confirmed it.", "category": "obscure"},
    61: {"fact": "Wilt Chamberlain's claim of having been with 20,000 women in his autobiography became one of the most talked-about (and disputed) off-court stories in league history.", "category": "random"},
    62: {"fact": "Charles Barkley never won an NBA championship despite being named MVP in 1993 and playing 16 seasons.", "category": "normal"},
    63: {"fact": "Karl Malone and John Stockton played together for the Utah Jazz for 18 seasons, one of the longest running duos in NBA history.", "category": "normal"},
    64: {"fact": "Karl Malone and John Stockton never won an NBA championship together, losing in the Finals twice to Michael Jordan's Bulls.", "category": "normal"},
    65: {"fact": "The Sacramento Kings hold the record for the longest playoff drought in major American professional sports at one point, missing the postseason for 16 straight seasons.", "category": "obscure"},
    66: {"fact": "The Los Angeles Clippers did not win a single playoff series for over three decades after moving from Buffalo to San Diego and then Los Angeles.", "category": "obscure"},
    67: {"fact": "The term 'Association' as slang for the NBA became popularized in hip-hop culture, particularly through references in songs by artists like Nelly.", "category": "random"},
    68: {"fact": "The NBA's in-season tournament, now called the NBA Cup, was introduced in the 2023-24 season with a specially designed court for group-stage games.", "category": "obscure"},
    69: {"fact": "Giannis Antetokounmpo grew up selling goods on the street in Athens, Greece, to help support his family before becoming an NBA MVP and champion.", "category": "normal"},
    70: {"fact": "Nikola Jokic was drafted 41st overall in the second round of the 2014 draft, famously during a Taco Bell commercial break on the draft broadcast.", "category": "obscure"},
    71: {"fact": "Manu Ginobili is one of only a few players to win an NBA championship, an Olympic gold medal, and a EuroLeague title.", "category": "obscure"},
    72: {"fact": "Dikembe Mutombo's finger wag after blocking a shot became one of the most iconic and imitated celebrations in NBA history.", "category": "normal"},
    73: {"fact": "The 'Malone' curse joke among fans refers to the fact that neither Karl Malone nor Moses Malone are related, despite sharing a last name and both being dominant power forwards/centers.", "category": "random"},
    74: {"fact": "Moses Malone is credited with popularizing the term 'fo, fo, fo' predicting a sweep through the 1983 playoffs; the 76ers actually went fo, fi, fo (losing only one game total).", "category": "obscure"},
    75: {"fact": "The three-point contest during All-Star Weekend was introduced in 1986 and was won by Larry Bird in its first three years.", "category": "normal"},
    76: {"fact": "Larry Bird reportedly walked into the locker room before the first three-point contest and asked the other competitors who was playing for second place.", "category": "random"},
    77: {"fact": "The Slam Dunk Contest was first held in the ABA in 1976, won by Julius Erving, who famously took off from the free-throw line for one of his dunks.", "category": "normal"},
    78: {"fact": "Michael Jordan won the NBA's version of the Slam Dunk Contest in 1988 with his own free-throw line dunk, echoing Erving's iconic move.", "category": "normal"},
    79: {"fact": "Spud Webb, at 5 feet 7 inches, won the 1986 Slam Dunk Contest, defeating his own Atlanta Hawks teammate Dominique Wilkins in the finals.", "category": "obscure"},
    80: {"fact": "The Atlanta Hawks franchise has had more relocations in its history than almost any other NBA team, having played in Buffalo, Moline, Tri-Cities, Milwaukee, and St. Louis before settling in Atlanta.", "category": "obscure"},
    81: {"fact": "Wilt Chamberlain's rookie season averages of over 37 points and 27 rebounds per game remain the best rookie season statistically in NBA history.", "category": "obscure"},
    82: {"fact": "The term 'triple-double' is believed to have been popularized by the Los Angeles Lakers' PR department during Magic Johnson's rookie season to promote his versatile stat lines.", "category": "obscure"},
    83: {"fact": "Russell Westbrook holds the record for most triple-doubles in a single season, and also passed Oscar Robertson for the most career triple-doubles in NBA history.", "category": "normal"},
    84: {"fact": "Oscar Robertson averaged a triple-double for an entire season in 1961-62, a feat that went unmatched for 55 years until Russell Westbrook repeated it.", "category": "normal"},
    85: {"fact": "The 'Jordan Rules' were a set of defensive tactics developed by the Detroit Pistons specifically designed to slow down Michael Jordan in the late 1980s.", "category": "obscure"},
    86: {"fact": "The NBA did not allow dunking during warm-ups or games for a period in the mid-20th century in college ball, and while dunking was always legal in the NBA, some early leagues discouraged it as showboating.", "category": "obscure"},
    87: {"fact": "Bill Russell was the first Black head coach in any major U.S. professional sports league, taking over as player-coach of the Celtics in 1966.", "category": "normal"},
    88: {"fact": "The Boston Celtics have retired more jersey numbers than any other NBA franchise.", "category": "obscure"},
    89: {"fact": "The Miami Heat's franchise has never lost a game in which they wore their 'Vice' city-edition jerseys during a notable early stretch, a stat frequently cited by fans as a superstition.", "category": "random"},
    90: {"fact": "Shaquille O'Neal changed his jersey number multiple times throughout his career, including wearing #34 with the Lakers and #32 or #33 with other teams.", "category": "obscure"},
    91: {"fact": "The tradition of retiring a jersey number for a player who never played for that specific franchise happened with Wilt Chamberlain's number being honored by multiple teams he played for.", "category": "obscure"},
    92: {"fact": "Elgin Baylor never won an NBA championship as a player despite being one of the most dominant scorers of the 1960s, often overshadowed by Bill Russell's Celtics dynasty.", "category": "obscure"},
    93: {"fact": "The longest game in NBA history was a six-overtime contest between the Indianapolis Olympians and Rochester Royals in 1951.", "category": "obscure"},
    94: {"fact": "The shortest coaching tenure in NBA history belongs to several coaches fired within days of being hired, often due to front office shakeups before a single game was even played.", "category": "random"},
    95: {"fact": "The NBA's play-in tournament was introduced in the 2020-21 season to give the 7th through 10th seeded teams a final chance to make the playoffs.", "category": "normal"},
    96: {"fact": "Wilt Chamberlain and Bill Russell combined played in an era before the three-point line existed, meaning some of their gaudiest scoring numbers came entirely from two-point range.", "category": "obscure"},
    97: {"fact": "The term 'and-one' for a shooting foul that results in a free throw became widely popularized through the AND1 streetball mixtape and shoe brand of the late 1990s.", "category": "random"},
    98: {"fact": "The Phoenix Suns have never won an NBA championship despite multiple Finals appearances, including runs led by Charles Barkley and later Chris Paul and Devin Booker.", "category": "normal"},
    99: {"fact": "The 'Fun Guy' nickname for Nikola Jokic became a popular internet meme referencing his laid-back demeanor despite being one of the most dominant players in the league.", "category": "random"},
    100: {"fact": "The NBA's 75th Anniversary season in 2021-22 featured commemorative court designs and a specially selected 75-player anniversary team honoring the league's history.", "category": "normal"},
}