"""
NBA 75th Anniversary Team (76 players named in 2021).
"""

nba_75th_anniversary_team = {
    "Allen Iverson": {
        "teams": [
            {"team": "Philadelphia 76ers", "years": "1996–2006, 2009–2010"},
            {"team": "Denver Nuggets", "years": "2006–2008"},
            {"team": "Detroit Pistons", "years": "2008–2009"},
            {"team": "Memphis Grizzlies", "years": "2009"},
        ],
        "position": "G",
        "career_points": 24368,
        "career_rebounds": 3394,
        "career_assists": 5624,
        "championships": {"count": 0, "years": []},
        "mvp": {"count": 1, "years": ['2001']},
        "finals_mvp": {"count": 0, "years": []},
        "all_star_selections": 11,
        "all_nba_selections": 7,
        "hof_year": 2016,
    },
    "Anthony Davis": {
        "teams": [
            {"team": "New Orleans Hornets / Pelicans", "years": "2012–2019"},
            {"team": "Los Angeles Lakers", "years": "2019–2021"},
        ],
        "position": "F/C",
        "career_points": 16988,
        "career_rebounds": 7420,
        "career_assists": 1732,
        "championships": {"count": 1, "years": ['2020']},
        "mvp": {"count": 0, "years": []},
        "finals_mvp": {"count": 0, "years": []},
        "all_star_selections": 9,
        "all_nba_selections": 4,
        "hof_year": None,
    },
    "Bill Russell": {
        "teams": [
            {"team": "Boston Celtics", "years": "1956–1969"},
        ],
        "position": "C",
        "career_points": 14522,
        "career_rebounds": 21620,
        "career_assists": 4100,
        "championships": {"count": 11, "years": ['1957', '1959', '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1968', '1969']},
        "mvp": {"count": 5, "years": ['1958', '1961', '1962', '1963', '1965']},
        "finals_mvp": {"count": 0, "years": []},
        "all_star_selections": 12,
        "all_nba_selections": 11,
        "hof_year": 1975,
    },
    "Bill Sharman": {
        "teams": [
            {"team": "Washington Capitols", "years": "1950–1951"},
            {"team": "Boston Celtics", "years": "1951–1961"},
        ],
        "position": "G",
        "career_points": 12665,
        "career_rebounds": 2779,
        "career_assists": 2101,
        "championships": {"count": 4, "years": ['1957', '1959', '1960', '1961']},
        "mvp": {"count": 0, "years": []},
        "finals_mvp": {"count": 0, "years": []},
        "all_star_selections": 8,
        "all_nba_selections": 7,
        "hof_year": 1976,
    },
    "Bill Walton": {
        "teams": [
            {"team": "Portland Trail Blazers", "years": "1974–1979"},
            {"team": "San Diego / Los Angeles Clippers", "years": "1979–1985"},
            {"team": "Boston Celtics", "years": "1985–1988"},
        ],
        "position": "C",
        "career_points": 6215,
        "career_rebounds": 4923,
        "career_assists": 1590,
        "championships": {"count": 2, "years": ['1977', '1986']},
        "mvp": {"count": 1, "years": ['1978']},
        "finals_mvp": {"count": 1, "years": ['1977']},
        "all_star_selections": 2,
        "all_nba_selections": 2,
        "hof_year": 1993,
    },
    "Billy Cunningham": {
        "teams": [
            {"team": "Philadelphia 76ers", "years": "1965–1972, 1974–1976"},
        ],
        "position": "F",
        "career_points": 13626,
        "career_rebounds": 6638,
        "career_assists": 2625,
        "championships": {"count": 1, "years": ['1967']},
        "mvp": {"count": 0, "years": []},
        "finals_mvp": {"count": 0, "years": []},
        "all_star_selections": 5,
        "all_nba_selections": 4,
        "hof_year": 1986,
    },
    "Bob Cousy": {
        "teams": [
            {"team": "Boston Celtics", "years": "1950–1963"},
            {"team": "Cincinnati Royals", "years": "1969–1970"},
        ],
        "position": "G",
        "career_points": 16960,
        "career_rebounds": 4786,
        "career_assists": 6955,
        "championships": {"count": 6, "years": ['1957', '1959', '1960', '1961', '1962', '1963']},
        "mvp": {"count": 1, "years": ['1957']},
        "finals_mvp": {"count": 0, "years": []},
        "all_star_selections": 13,
        "all_nba_selections": 12,
        "hof_year": 1971,
    },
    "Bob McAdoo": {
        "teams": [
            {"team": "Buffalo Braves", "years": "1972–1976"},
            {"team": "New York Knicks", "years": "1976–1979"},
            {"team": "Boston Celtics", "years": "1979"},
            {"team": "Detroit Pistons", "years": "1979–1981"},
            {"team": "New Jersey Nets", "years": "1981"},
            {"team": "Los Angeles Lakers", "years": "1981–1985"},
            {"team": "Philadelphia 76ers", "years": "1986"},
        ],
        "position": "F/C",
        "career_points": 18787,
        "career_rebounds": 8048,
        "career_assists": 1951,
        "championships": {"count": 2, "years": ['1982', '1985']},
        "mvp": {"count": 1, "years": ['1975']},
        "finals_mvp": {"count": 0, "years": []},
        "all_star_selections": 5,
        "all_nba_selections": 2,
        "hof_year": 2000,
    },
    "Bob Pettit": {
        "teams": [
            {"team": "Milwaukee / St. Louis Hawks", "years": "1954–1965"},
        ],
        "position": "F",
        "career_points": 20880,
        "career_rebounds": 12849,
        "career_assists": 2369,
        "championships": {"count": 1, "years": ['1958']},
        "mvp": {"count": 2, "years": ['1956', '1959']},
        "finals_mvp": {"count": 0, "years": []},
        "all_star_selections": 11,
        "all_nba_selections": 11,
        "hof_year": 1971,
    },
    "Carmelo Anthony": {
        "teams": [
            {"team": "Denver Nuggets", "years": "2003–2011"},
            {"team": "New York Knicks", "years": "2011–2017"},
            {"team": "Oklahoma City Thunder", "years": "2017–2018"},
            {"team": "Houston Rockets", "years": "2018–2019"},
            {"team": "Portland Trail Blazers", "years": "2019–2021"},
        ],
        "position": "F",
        "career_points": 27370,
        "career_rebounds": 7520,
        "career_assists": 3354,
        "championships": {"count": 0, "years": []},
        "mvp": {"count": 0, "years": []},
        "finals_mvp": {"count": 0, "years": []},
        "all_star_selections": 10,
        "all_nba_selections": 6,
        "hof_year": 2025,
    },
    "Charles Barkley": {
        "teams": [
            {"team": "Philadelphia 76ers", "years": "1984–1992"},
            {"team": "Phoenix Suns", "years": "1992–1996"},
            {"team": "Houston Rockets", "years": "1996–2000"},
        ],
        "position": "F",
        "career_points": 23757,
        "career_rebounds": 12546,
        "career_assists": 4215,
        "championships": {"count": 0, "years": []},
        "mvp": {"count": 1, "years": ['1993']},
        "finals_mvp": {"count": 0, "years": []},
        "all_star_selections": 11,
        "all_nba_selections": 11,
        "hof_year": 2006,
    },
    "Chris Paul": {
        "teams": [
            {"team": "New Orleans Hornets", "years": "2005–2011"},
            {"team": "Los Angeles Clippers", "years": "2011–2017"},
            {"team": "Houston Rockets", "years": "2017–2019"},
            {"team": "Oklahoma City Thunder", "years": "2019–2020"},
            {"team": "Phoenix Suns", "years": "2020–2021"},
        ],
        "position": "G",
        "career_points": 19978,
        "career_rebounds": 4923,
        "career_assists": 10275,
        "championships": {"count": 0, "years": []},
        "mvp": {"count": 0, "years": []},
        "finals_mvp": {"count": 0, "years": []},
        "all_star_selections": 11,
        "all_nba_selections": 10,
        "hof_year": None,
    },
    "Clyde Drexler": {
        "teams": [
            {"team": "Portland Trail Blazers", "years": "1983–1995"},
            {"team": "Houston Rockets", "years": "1995–1998"},
        ],
        "position": "G",
        "career_points": 22195,
        "career_rebounds": 6677,
        "career_assists": 6125,
        "championships": {"count": 1, "years": ['1995']},
        "mvp": {"count": 0, "years": []},
        "finals_mvp": {"count": 0, "years": []},
        "all_star_selections": 10,
        "all_nba_selections": 5,
        "hof_year": 2004,
    },
    "Damian Lillard": {
        "teams": [
            {"team": "Portland Trail Blazers", "years": "2012–2021"},
        ],
        "position": "G",
        "career_points": 16815,
        "career_rebounds": 2856,
        "career_assists": 4514,
        "championships": {"count": 0, "years": []},
        "mvp": {"count": 0, "years": []},
        "finals_mvp": {"count": 0, "years": []},
        "all_star_selections": 6,
        "all_nba_selections": 6,
        "hof_year": None,
    },
    "Dave Bing": {
        "teams": [
            {"team": "Detroit Pistons", "years": "1966–1975"},
            {"team": "Washington Bullets", "years": "1975–1977"},
            {"team": "Boston Celtics", "years": "1977–1978"},
        ],
        "position": "G",
        "career_points": 18327,
        "career_rebounds": 3420,
        "career_assists": 5397,
        "championships": {"count": 0, "years": []},
        "mvp": {"count": 0, "years": []},
        "finals_mvp": {"count": 0, "years": []},
        "all_star_selections": 7,
        "all_nba_selections": 3,
        "hof_year": 1990,
    },
    "Dave Cowens": {
        "teams": [
            {"team": "Boston Celtics", "years": "1970–1980"},
            {"team": "Milwaukee Bucks", "years": "1982–1983"},
        ],
        "position": "C",
        "career_points": 13516,
        "career_rebounds": 10444,
        "career_assists": 2910,
        "championships": {"count": 2, "years": ['1974', '1976']},
        "mvp": {"count": 1, "years": ['1973']},
        "finals_mvp": {"count": 0, "years": []},
        "all_star_selections": 7,
        "all_nba_selections": 3,
        "hof_year": 1991,
    },
    "Dave DeBusschere": {
        "teams": [
            {"team": "Detroit Pistons", "years": "1962–1968"},
            {"team": "New York Knicks", "years": "1968–1974"},
        ],
        "position": "F",
        "career_points": 14053,
        "career_rebounds": 9618,
        "career_assists": 2497,
        "championships": {"count": 2, "years": ['1970', '1973']},
        "mvp": {"count": 0, "years": []},
        "finals_mvp": {"count": 0, "years": []},
        "all_star_selections": 8,
        "all_nba_selections": 1,
        "hof_year": 1983,
    },
    "David Robinson": {
        "teams": [
            {"team": "San Antonio Spurs", "years": "1989–2003"},
        ],
        "position": "C",
        "career_points": 20790,
        "career_rebounds": 10497,
        "career_assists": 2441,
        "championships": {"count": 2, "years": ['1999', '2003']},
        "mvp": {"count": 1, "years": ['1995']},
        "finals_mvp": {"count": 0, "years": []},
        "all_star_selections": 10,
        "all_nba_selections": 10,
        "hof_year": 2009,
    },
    "Dennis Rodman": {
        "teams": [
            {"team": "Detroit Pistons", "years": "1986–1993"},
            {"team": "San Antonio Spurs", "years": "1993–1995"},
            {"team": "Chicago Bulls", "years": "1995–1998"},
            {"team": "Los Angeles Lakers", "years": "1999"},
            {"team": "Dallas Mavericks", "years": "2000"},
        ],
        "position": "F",
        "career_points": 6683,
        "career_rebounds": 11954,
        "career_assists": 1600,
        "championships": {"count": 5, "years": ['1989', '1990', '1996', '1997', '1998']},
        "mvp": {"count": 0, "years": []},
        "finals_mvp": {"count": 0, "years": []},
        "all_star_selections": 2,
        "all_nba_selections": 2,
        "hof_year": 2011,
    },
    "Dirk Nowitzki": {
        "teams": [
            {"team": "Dallas Mavericks", "years": "1998–2019"},
        ],
        "position": "F",
        "career_points": 31560,
        "career_rebounds": 11489,
        "career_assists": 3651,
        "championships": {"count": 1, "years": ['2011']},
        "mvp": {"count": 1, "years": ['2007']},
        "finals_mvp": {"count": 1, "years": ['2011']},
        "all_star_selections": 14,
        "all_nba_selections": 12,
        "hof_year": 2023,
    },
    "Dolph Schayes": {
        "teams": [
            {"team": "Syracuse Nationals / Philadelphia 76ers", "years": "1949–1964"},
        ],
        "position": "F",
        "career_points": 18438,
        "career_rebounds": 11256,
        "career_assists": 3072,
        "championships": {"count": 1, "years": ['1955']},
        "mvp": {"count": 0, "years": []},
        "finals_mvp": {"count": 0, "years": []},
        "all_star_selections": 12,
        "all_nba_selections": 12,
        "hof_year": 1973,
    },
    "Dominique Wilkins": {
        "teams": [
            {"team": "Atlanta Hawks", "years": "1982–1994"},
            {"team": "Los Angeles Clippers", "years": "1994"},
            {"team": "Boston Celtics", "years": "1994–1995"},
            {"team": "San Antonio Spurs", "years": "1996–1997"},
            {"team": "Orlando Magic", "years": "1999"},
        ],
        "position": "F",
        "career_points": 26668,
        "career_rebounds": 7169,
        "career_assists": 2677,
        "championships": {"count": 0, "years": []},
        "mvp": {"count": 0, "years": []},
        "finals_mvp": {"count": 0, "years": []},
        "all_star_selections": 9,
        "all_nba_selections": 7,
        "hof_year": 2006,
    },
    "Dwyane Wade": {
        "teams": [
            {"team": "Miami Heat", "years": "2003–2016, 2018–2019"},
            {"team": "Chicago Bulls", "years": "2016–2017"},
            {"team": "Cleveland Cavaliers", "years": "2017–2018"},
        ],
        "position": "G",
        "career_points": 23165,
        "career_rebounds": 4933,
        "career_assists": 5701,
        "championships": {"count": 3, "years": ['2006', '2012', '2013']},
        "mvp": {"count": 0, "years": []},
        "finals_mvp": {"count": 1, "years": ['2006']},
        "all_star_selections": 13,
        "all_nba_selections": 8,
        "hof_year": 2023,
    },
    "Earl Monroe": {
        "teams": [
            {"team": "Baltimore Bullets", "years": "1967–1971"},
            {"team": "New York Knicks", "years": "1971–1980"},
        ],
        "position": "G",
        "career_points": 17454,
        "career_rebounds": 2796,
        "career_assists": 3594,
        "championships": {"count": 1, "years": ['1973']},
        "mvp": {"count": 0, "years": []},
        "finals_mvp": {"count": 0, "years": []},
        "all_star_selections": 4,
        "all_nba_selections": 1,
        "hof_year": 1990,
    },
    "Elgin Baylor": {
        "teams": [
            {"team": "Minneapolis / Los Angeles Lakers", "years": "1958–1971"},
        ],
        "position": "F",
        "career_points": 23149,
        "career_rebounds": 11463,
        "career_assists": 3650,
        "championships": {"count": 0, "years": []},
        "mvp": {"count": 0, "years": []},
        "finals_mvp": {"count": 0, "years": []},
        "all_star_selections": 11,
        "all_nba_selections": 10,
        "hof_year": 1977,
    },
    "Elvin Hayes": {
        "teams": [
            {"team": "San Diego / Houston Rockets", "years": "1968–1972, 1981–1984"},
            {"team": "Baltimore / Capital / Washington Bullets", "years": "1972–1981"},
        ],
        "position": "F/C",
        "career_points": 27313,
        "career_rebounds": 16279,
        "career_assists": 2398,
        "championships": {"count": 1, "years": ['1978']},
        "mvp": {"count": 0, "years": []},
        "finals_mvp": {"count": 0, "years": []},
        "all_star_selections": 12,
        "all_nba_selections": 6,
        "hof_year": 1990,
    },
    "Gary Payton": {
        "teams": [
            {"team": "Seattle SuperSonics", "years": "1990–2003"},
            {"team": "Milwaukee Bucks", "years": "2003"},
            {"team": "Los Angeles Lakers", "years": "2003–2004"},
            {"team": "Boston Celtics", "years": "2004–2005"},
            {"team": "Miami Heat", "years": "2005–2007"},
        ],
        "position": "G",
        "career_points": 21813,
        "career_rebounds": 5269,
        "career_assists": 8966,
        "championships": {"count": 1, "years": ['2006']},
        "mvp": {"count": 0, "years": []},
        "finals_mvp": {"count": 0, "years": []},
        "all_star_selections": 9,
        "all_nba_selections": 9,
        "hof_year": 2013,
    },
    "George Gervin": {
        "teams": [
            {"team": "San Antonio Spurs", "years": "1976–1985"},
            {"team": "Chicago Bulls", "years": "1985–1986"},
        ],
        "position": "G",
        "career_points": 20708,
        "career_rebounds": 3607,
        "career_assists": 2214,
        "championships": {"count": 0, "years": []},
        "mvp": {"count": 0, "years": []},
        "finals_mvp": {"count": 0, "years": []},
        "all_star_selections": 9,
        "all_nba_selections": 7,
        "hof_year": 1996,
    },
    "George Mikan": {
        "teams": [
            {"team": "Minneapolis Lakers", "years": "1948–1954, 1956"},
        ],
        "position": "C",
        "career_points": 10156,
        "career_rebounds": 4167,
        "career_assists": 1245,
        "championships": {"count": 5, "years": ['1949', '1950', '1952', '1953', '1954']},
        "mvp": {"count": 0, "years": []},
        "finals_mvp": {"count": 0, "years": []},
        "all_star_selections": 4,
        "all_nba_selections": 6,
        "hof_year": 1959,
    },
    "Giannis Antetokounmpo": {
        "teams": [
            {"team": "Milwaukee Bucks", "years": "2013–2021"},
        ],
        "position": "F",
        "career_points": 12319,
        "career_rebounds": 5371,
        "career_assists": 2632,
        "championships": {"count": 1, "years": ['2021']},
        "mvp": {"count": 2, "years": ['2019', '2020']},
        "finals_mvp": {"count": 1, "years": ['2021']},
        "all_star_selections": 5,
        "all_nba_selections": 5,
        "hof_year": None,
    },
    "Hakeem Olajuwon": {
        "teams": [
            {"team": "Houston Rockets", "years": "1984–2001"},
            {"team": "Toronto Raptors", "years": "2001–2002"},
        ],
        "position": "C",
        "career_points": 26946,
        "career_rebounds": 13748,
        "career_assists": 3058,
        "championships": {"count": 2, "years": ['1994', '1995']},
        "mvp": {"count": 1, "years": ['1994']},
        "finals_mvp": {"count": 2, "years": ['1994', '1995']},
        "all_star_selections": 12,
        "all_nba_selections": 12,
        "hof_year": 2008,
    },
    "Hal Greer": {
        "teams": [
            {"team": "Syracuse Nationals / Philadelphia 76ers", "years": "1958–1973"},
        ],
        "position": "G",
        "career_points": 21586,
        "career_rebounds": 5665,
        "career_assists": 4540,
        "championships": {"count": 1, "years": ['1967']},
        "mvp": {"count": 0, "years": []},
        "finals_mvp": {"count": 0, "years": []},
        "all_star_selections": 10,
        "all_nba_selections": 7,
        "hof_year": 1982,
    },
    "Isiah Thomas": {
        "teams": [
            {"team": "Detroit Pistons", "years": "1981–1994"},
        ],
        "position": "G",
        "career_points": 18822,
        "career_rebounds": 3478,
        "career_assists": 9061,
        "championships": {"count": 2, "years": ['1989', '1990']},
        "mvp": {"count": 0, "years": []},
        "finals_mvp": {"count": 1, "years": ['1990']},
        "all_star_selections": 12,
        "all_nba_selections": 5,
        "hof_year": 2000,
    },
    "James Harden": {
        "teams": [
            {"team": "Oklahoma City Thunder", "years": "2009–2012"},
            {"team": "Houston Rockets", "years": "2012–2021"},
            {"team": "Brooklyn Nets", "years": "2021"},
            {"team": "Los Angeles", "years": "2023"},
        ],
        "position": "G",
        "career_points": 22045,
        "career_rebounds": 4794,
        "career_assists": 5730,
        "championships": {"count": 0, "years": []},
        "mvp": {"count": 1, "years": ['2018']},
        "finals_mvp": {"count": 0, "years": []},
        "all_star_selections": 9,
        "all_nba_selections": 7,
        "hof_year": None,
    },
    "James Worthy": {
        "teams": [
            {"team": "Los Angeles Lakers", "years": "1982–1994"},
        ],
        "position": "F",
        "career_points": 16320,
        "career_rebounds": 4708,
        "career_assists": 2791,
        "championships": {"count": 3, "years": ['1985', '1987', '1988']},
        "mvp": {"count": 0, "years": []},
        "finals_mvp": {"count": 1, "years": ['1988']},
        "all_star_selections": 7,
        "all_nba_selections": 2,
        "hof_year": 2003,
    },
    "Jason Kidd": {
        "teams": [
            {"team": "Dallas Mavericks", "years": "1994–1996, 2008–2012"},
            {"team": "Phoenix Suns", "years": "1996–2001"},
            {"team": "New Jersey Nets", "years": "2001–2008"},
            {"team": "New York Knicks", "years": "2012–2013"},
        ],
        "position": "G",
        "career_points": 17529,
        "career_rebounds": 8725,
        "career_assists": 12091,
        "championships": {"count": 1, "years": ['2011']},
        "mvp": {"count": 0, "years": []},
        "finals_mvp": {"count": 0, "years": []},
        "all_star_selections": 10,
        "all_nba_selections": 6,
        "hof_year": 2018,
    },
    "Jerry Lucas": {
        "teams": [
            {"team": "Cincinnati Royals", "years": "1963–1969"},
            {"team": "San Francisco Warriors", "years": "1969–1971"},
            {"team": "New York Knicks", "years": "1971–1974"},
        ],
        "position": "F",
        "career_points": 14053,
        "career_rebounds": 12942,
        "career_assists": 2732,
        "championships": {"count": 1, "years": ['1973']},
        "mvp": {"count": 0, "years": []},
        "finals_mvp": {"count": 0, "years": []},
        "all_star_selections": 7,
        "all_nba_selections": 5,
        "hof_year": 1980,
    },
    "Jerry West": {
        "teams": [
            {"team": "Los Angeles Lakers", "years": "1960–1974"},
        ],
        "position": "G",
        "career_points": 25192,
        "career_rebounds": 5366,
        "career_assists": 6238,
        "championships": {"count": 1, "years": ['1972']},
        "mvp": {"count": 0, "years": []},
        "finals_mvp": {"count": 1, "years": ['1969']},
        "all_star_selections": 14,
        "all_nba_selections": 12,
        "hof_year": 1980,
    },
    "John Havlicek": {
        "teams": [
            {"team": "Boston Celtics", "years": "1962–1978"},
        ],
        "position": "F/G",
        "career_points": 26395,
        "career_rebounds": 8007,
        "career_assists": 6114,
        "championships": {"count": 8, "years": ['1963', '1964', '1965', '1966', '1968', '1969', '1974', '1976']},
        "mvp": {"count": 0, "years": []},
        "finals_mvp": {"count": 1, "years": ['1974']},
        "all_star_selections": 13,
        "all_nba_selections": 11,
        "hof_year": 1984,
    },
    "John Stockton": {
        "teams": [
            {"team": "Utah Jazz", "years": "1984–2003"},
        ],
        "position": "G",
        "career_points": 19711,
        "career_rebounds": 4051,
        "career_assists": 15806,
        "championships": {"count": 0, "years": []},
        "mvp": {"count": 0, "years": []},
        "finals_mvp": {"count": 0, "years": []},
        "all_star_selections": 10,
        "all_nba_selections": 11,
        "hof_year": 2009,
    },
    "Julius Erving": {
        "teams": [
            {"team": "Philadelphia 76ers", "years": "1976–1987"},
        ],
        "position": "F",
        "career_points": 18364,
        "career_rebounds": 5601,
        "career_assists": 3224,
        "championships": {"count": 1, "years": ['1983']},
        "mvp": {"count": 1, "years": ['1981']},
        "finals_mvp": {"count": 0, "years": []},
        "all_star_selections": 11,
        "all_nba_selections": 7,
        "hof_year": 1993,
    },
    "Kareem Abdul-Jabbar": {
        "teams": [
            {"team": "Milwaukee Bucks", "years": "1969–1975"},
            {"team": "Los Angeles Lakers", "years": "1975–1989"},
        ],
        "position": "C",
        "career_points": 38387,
        "career_rebounds": 17440,
        "career_assists": 5660,
        "championships": {"count": 6, "years": ['1971', '1980', '1982', '1985', '1987', '1988']},
        "mvp": {"count": 6, "years": ['1971', '1972', '1974', '1976', '1977', '1980']},
        "finals_mvp": {"count": 2, "years": ['1971', '1985']},
        "all_star_selections": 19,
        "all_nba_selections": 15,
        "hof_year": 1995,
    },
    "Karl Malone": {
        "teams": [
            {"team": "Utah Jazz", "years": "1985–2003"},
            {"team": "Los Angeles Lakers", "years": "2003–2004"},
        ],
        "position": "F",
        "career_points": 36928,
        "career_rebounds": 14968,
        "career_assists": 5248,
        "championships": {"count": 0, "years": []},
        "mvp": {"count": 2, "years": ['1997', '1999']},
        "finals_mvp": {"count": 0, "years": []},
        "all_star_selections": 14,
        "all_nba_selections": 14,
        "hof_year": 2010,
    },
    "Kawhi Leonard": {
        "teams": [
            {"team": "San Antonio Spurs", "years": "2011–2018"},
            {"team": "Toronto Raptors", "years": "2018–2019"},
            {"team": "Los Angeles Clippers", "years": "2019–2021"},
        ],
        "position": "F",
        "career_points": 11085,
        "career_rebounds": 3689,
        "career_assists": 1672,
        "championships": {"count": 2, "years": ['2014', '2019']},
        "mvp": {"count": 0, "years": []},
        "finals_mvp": {"count": 2, "years": ['2014', '2019']},
        "all_star_selections": 5,
        "all_nba_selections": 5,
        "hof_year": None,
    },
    "Kevin Durant": {
        "teams": [
            {"team": "Seattle SuperSonics / Oklahoma City Thunder", "years": "2007–2016"},
            {"team": "Golden State Warriors", "years": "2016–2019"},
            {"team": "Brooklyn Nets", "years": "2019–2023"},
            {"team": "Phoenix Suns", "years": "2023–2025"},
        ],
        "position": "F",
        "career_points": 28924,
        "career_rebounds": 7454,
        "career_assists": 4645,
        "championships": {"count": 2, "years": ['2017', '2018']},
        "mvp": {"count": 1, "years": ['2014']},
        "finals_mvp": {"count": 2, "years": ['2017', '2018']},
        "all_star_selections": 14,
        "all_nba_selections": 11,
        "hof_year": None,
    },
    "Kevin Garnett": {
        "teams": [
            {"team": "Minnesota Timberwolves", "years": "1995–2007, 2015–2016"},
            {"team": "Boston Celtics", "years": "2007–2013"},
            {"team": "Brooklyn Nets", "years": "2013–2015"},
        ],
        "position": "F/C",
        "career_points": 26071,
        "career_rebounds": 14662,
        "career_assists": 5445,
        "championships": {"count": 1, "years": ['2008']},
        "mvp": {"count": 1, "years": ['2004']},
        "finals_mvp": {"count": 0, "years": []},
        "all_star_selections": 15,
        "all_nba_selections": 9,
        "hof_year": 2020,
    },
    "Kevin McHale": {
        "teams": [
            {"team": "Boston Celtics", "years": "1980–1993"},
        ],
        "position": "F",
        "career_points": 17335,
        "career_rebounds": 7122,
        "career_assists": 1670,
        "championships": {"count": 3, "years": ['1981', '1984', '1986']},
        "mvp": {"count": 0, "years": []},
        "finals_mvp": {"count": 0, "years": []},
        "all_star_selections": 7,
        "all_nba_selections": 1,
        "hof_year": 1999,
    },
    "Kobe Bryant": {
        "teams": [
            {"team": "Los Angeles Lakers", "years": "1996–2016"},
        ],
        "position": "G",
        "career_points": 33643,
        "career_rebounds": 7047,
        "career_assists": 6306,
        "championships": {"count": 5, "years": ['2000', '2001', '2002', '2009', '2010']},
        "mvp": {"count": 1, "years": ['2008']},
        "finals_mvp": {"count": 2, "years": ['2009', '2010']},
        "all_star_selections": 18,
        "all_nba_selections": 15,
        "hof_year": 2020,
    },
    "Larry Bird": {
        "teams": [
            {"team": "Boston Celtics", "years": "1979–1992"},
        ],
        "position": "F",
        "career_points": 21791,
        "career_rebounds": 8974,
        "career_assists": 5695,
        "championships": {"count": 3, "years": ['1981', '1984', '1986']},
        "mvp": {"count": 3, "years": ['1984', '1985', '1986']},
        "finals_mvp": {"count": 2, "years": ['1984', '1986']},
        "all_star_selections": 12,
        "all_nba_selections": 10,
        "hof_year": 1998,
    },
    "LeBron James": {
        "teams": [
            {"team": "Cleveland Cavaliers", "years": "2003–2010, 2014–2018"},
            {"team": "Miami Heat", "years": "2010–2014"},
            {"team": "Los Angeles Lakers", "years": "2018–2021"},
        ],
        "position": "F",
        "career_points": 40017,
        "career_rebounds": 10847,
        "career_assists": 11046,
        "championships": {"count": 4, "years": ['2012', '2013', '2016', '2020']},
        "mvp": {"count": 4, "years": ['2009', '2010', '2012', '2013']},
        "finals_mvp": {"count": 4, "years": ['2012', '2013', '2016', '2020']},
        "all_star_selections": 21,
        "all_nba_selections": 20,
        "hof_year": None,
    },
    "Lenny Wilkens": {
        "teams": [
            {"team": "St. Louis Hawks", "years": "1960−1968"},
            {"team": "Seattle SuperSonics", "years": "1968–1972"},
            {"team": "Cleveland Cavaliers", "years": "1972–1974"},
            {"team": "Portland Trail Blazers", "years": "1974–1975"},
        ],
        "position": "G",
        "career_points": 17772,
        "career_rebounds": 5030,
        "career_assists": 7211,
        "championships": {"count": 0, "years": []},
        "mvp": {"count": 0, "years": []},
        "finals_mvp": {"count": 0, "years": []},
        "all_star_selections": 9,
        "all_nba_selections": 0,
        "hof_year": 1989,
    },
    "Magic Johnson": {
        "teams": [
            {"team": "Los Angeles Lakers", "years": "1979–1991, 1996"},
        ],
        "position": "G",
        "career_points": 17707,
        "career_rebounds": 6559,
        "career_assists": 10141,
        "championships": {"count": 5, "years": ['1980', '1982', '1985', '1987', '1988']},
        "mvp": {"count": 3, "years": ['1987', '1989', '1990']},
        "finals_mvp": {"count": 3, "years": ['1980', '1982', '1987']},
        "all_star_selections": 12,
        "all_nba_selections": 10,
        "hof_year": 2002,
    },
    "Michael Jordan": {
        "teams": [
            {"team": "Chicago Bulls", "years": "1984–1993, 1995–1998"},
            {"team": "Washington Wizards", "years": "2001–2003"},
        ],
        "position": "G",
        "career_points": 32292,
        "career_rebounds": 6672,
        "career_assists": 5633,
        "championships": {"count": 6, "years": ['1991', '1992', '1993', '1996', '1997', '1998']},
        "mvp": {"count": 5, "years": ['1988', '1991', '1992', '1996', '1998']},
        "finals_mvp": {"count": 6, "years": ['1991', '1992', '1993', '1996', '1997', '1998']},
        "all_star_selections": 14,
        "all_nba_selections": 11,
        "hof_year": 2009,
    },
    "Moses Malone": {
        "teams": [
            {"team": "Buffalo Braves", "years": "1976"},
            {"team": "Houston Rockets", "years": "1976–1982"},
            {"team": "Philadelphia 76ers", "years": "1982–1986, 1993–1994"},
            {"team": "Washington Bullets", "years": "1986–1988"},
            {"team": "Atlanta Hawks", "years": "1988–1991"},
            {"team": "Milwaukee Bucks", "years": "1991–1993"},
            {"team": "San Antonio Spurs", "years": "1994–1995"},
        ],
        "position": "C",
        "career_points": 27409,
        "career_rebounds": 16212,
        "career_assists": 1796,
        "championships": {"count": 1, "years": ['1983']},
        "mvp": {"count": 3, "years": ['1979', '1982', '1983']},
        "finals_mvp": {"count": 1, "years": ['1983']},
        "all_star_selections": 12,
        "all_nba_selections": 8,
        "hof_year": 2001,
    },
    "Nate Archibald": {
        "teams": [
            {"team": "Cincinnati Royals / Kansas City-Omaha / Kansas City Kings", "years": "1970–1976"},
            {"team": "New York Nets", "years": "1976–1977"},
            {"team": "Boston Celtics", "years": "1978–1983"},
            {"team": "Milwaukee Bucks", "years": "1983–1984"},
        ],
        "position": "G",
        "career_points": 16481,
        "career_rebounds": 2046,
        "career_assists": 6476,
        "championships": {"count": 1, "years": ['1981']},
        "mvp": {"count": 0, "years": []},
        "finals_mvp": {"count": 0, "years": []},
        "all_star_selections": 6,
        "all_nba_selections": 5,
        "hof_year": 1991,
    },
    "Nate Thurmond": {
        "teams": [
            {"team": "San Francisco / Golden State Warriors", "years": "1963–1974"},
            {"team": "Chicago Bulls", "years": "1974–1975"},
            {"team": "Cleveland Cavaliers", "years": "1975–1977"},
        ],
        "position": "C",
        "career_points": 14437,
        "career_rebounds": 14464,
        "career_assists": 2575,
        "championships": {"count": 0, "years": []},
        "mvp": {"count": 0, "years": []},
        "finals_mvp": {"count": 0, "years": []},
        "all_star_selections": 7,
        "all_nba_selections": 0,
        "hof_year": 1985,
    },
    "Oscar Robertson": {
        "teams": [
            {"team": "Cincinnati Royals", "years": "1960–1970"},
            {"team": "Milwaukee Bucks", "years": "1970–1974"},
        ],
        "position": "G",
        "career_points": 26710,
        "career_rebounds": 7804,
        "career_assists": 9887,
        "championships": {"count": 1, "years": ['1971']},
        "mvp": {"count": 1, "years": ['1964']},
        "finals_mvp": {"count": 0, "years": []},
        "all_star_selections": 12,
        "all_nba_selections": 11,
        "hof_year": 1980,
    },
    "Patrick Ewing": {
        "teams": [
            {"team": "New York Knicks", "years": "1985–2000"},
            {"team": "Seattle SuperSonics", "years": "2000–2001"},
            {"team": "Orlando Magic", "years": "2001–2002"},
        ],
        "position": "C",
        "career_points": 24815,
        "career_rebounds": 11607,
        "career_assists": 2215,
        "championships": {"count": 0, "years": []},
        "mvp": {"count": 0, "years": []},
        "finals_mvp": {"count": 0, "years": []},
        "all_star_selections": 11,
        "all_nba_selections": 7,
        "hof_year": 2008,
    },
    "Paul Arizin": {
        "teams": [
            {"team": "Philadelphia Warriors", "years": "1950–1952, 1954–1962"},
        ],
        "position": "F",
        "career_points": 16266,
        "career_rebounds": 6129,
        "career_assists": 1665,
        "championships": {"count": 1, "years": ['1956']},
        "mvp": {"count": 0, "years": []},
        "finals_mvp": {"count": 0, "years": []},
        "all_star_selections": 10,
        "all_nba_selections": 4,
        "hof_year": 1978,
    },
    "Paul Pierce": {
        "teams": [
            {"team": "Boston Celtics", "years": "1998–2013"},
            {"team": "Brooklyn Nets", "years": "2013–2014"},
            {"team": "Washington Wizards", "years": "2014–2015"},
            {"team": "Los Angeles Clippers", "years": "2015–2017"},
        ],
        "position": "F",
        "career_points": 26397,
        "career_rebounds": 7527,
        "career_assists": 4708,
        "championships": {"count": 1, "years": ['2008']},
        "mvp": {"count": 0, "years": []},
        "finals_mvp": {"count": 1, "years": ['2008']},
        "all_star_selections": 10,
        "all_nba_selections": 4,
        "hof_year": 2021,
    },
    "Pete Maravich": {
        "teams": [
            {"team": "Atlanta Hawks", "years": "1970–1974"},
            {"team": "New Orleans / Utah Jazz", "years": "1974–1980"},
            {"team": "Boston Celtics", "years": "1980"},
        ],
        "position": "G",
        "career_points": 15948,
        "career_rebounds": 2747,
        "career_assists": 3563,
        "championships": {"count": 0, "years": []},
        "mvp": {"count": 0, "years": []},
        "finals_mvp": {"count": 0, "years": []},
        "all_star_selections": 5,
        "all_nba_selections": 4,
        "hof_year": 1987,
    },
    "Ray Allen": {
        "teams": [
            {"team": "Milwaukee Bucks", "years": "1996–2003"},
            {"team": "Seattle SuperSonics", "years": "2003–2007"},
            {"team": "Boston Celtics", "years": "2007–2012"},
            {"team": "Miami Heat", "years": "2012–2014"},
        ],
        "position": "G",
        "career_points": 24505,
        "career_rebounds": 5272,
        "career_assists": 4361,
        "championships": {"count": 2, "years": ['2008', '2013']},
        "mvp": {"count": 0, "years": []},
        "finals_mvp": {"count": 0, "years": []},
        "all_star_selections": 10,
        "all_nba_selections": 2,
        "hof_year": 2018,
    },
    "Reggie Miller": {
        "teams": [
            {"team": "Indiana Pacers", "years": "1987–2005"},
        ],
        "position": "G",
        "career_points": 25279,
        "career_rebounds": 4182,
        "career_assists": 4141,
        "championships": {"count": 0, "years": []},
        "mvp": {"count": 0, "years": []},
        "finals_mvp": {"count": 0, "years": []},
        "all_star_selections": 5,
        "all_nba_selections": 3,
        "hof_year": 2012,
    },
    "Rick Barry": {
        "teams": [
            {"team": "San Francisco / Golden State Warriors", "years": "1965–1967, 1972–1978"},
            {"team": "Houston Rockets", "years": "1978–1980"},
        ],
        "position": "F",
        "career_points": 18395,
        "career_rebounds": 5168,
        "career_assists": 4017,
        "championships": {"count": 1, "years": ['1975']},
        "mvp": {"count": 0, "years": []},
        "finals_mvp": {"count": 1, "years": ['1975']},
        "all_star_selections": 8,
        "all_nba_selections": 6,
        "hof_year": 1987,
    },
    "Robert Parish": {
        "teams": [
            {"team": "Golden State Warriors", "years": "1976–1980"},
            {"team": "Boston Celtics", "years": "1980–1994"},
            {"team": "Charlotte Hornets", "years": "1994–1996"},
            {"team": "Chicago Bulls", "years": "1996–1997"},
        ],
        "position": "C",
        "career_points": 23334,
        "career_rebounds": 14715,
        "career_assists": 2180,
        "championships": {"count": 4, "years": ['1981', '1984', '1986', '1997']},
        "mvp": {"count": 0, "years": []},
        "finals_mvp": {"count": 0, "years": []},
        "all_star_selections": 9,
        "all_nba_selections": 2,
        "hof_year": 2003,
    },
    "Russell Westbrook": {
        "teams": [
            {"team": "Oklahoma City Thunder", "years": "2008–2019"},
            {"team": "Houston Rockets", "years": "2019–2020"},
            {"team": "Washington Wizards", "years": "2020–2021"},
        ],
        "position": "G",
        "career_points": 26473,
        "career_rebounds": 6961,
        "career_assists": 8061,
        "championships": {"count": 0, "years": []},
        "mvp": {"count": 1, "years": ['2017']},
        "finals_mvp": {"count": 0, "years": []},
        "all_star_selections": 9,
        "all_nba_selections": 9,
        "hof_year": None,
    },
    "Sam Jones": {
        "teams": [
            {"team": "Boston Celtics", "years": "1957–1969"},
        ],
        "position": "G",
        "career_points": 15411,
        "career_rebounds": 4305,
        "career_assists": 2209,
        "championships": {"count": 10, "years": ['1959', '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1968', '1969']},
        "mvp": {"count": 0, "years": []},
        "finals_mvp": {"count": 0, "years": []},
        "all_star_selections": 5,
        "all_nba_selections": 3,
        "hof_year": 1984,
    },
    "Scottie Pippen": {
        "teams": [
            {"team": "Chicago Bulls", "years": "1987–1998, 2003–2004"},
            {"team": "Houston Rockets", "years": "1999"},
            {"team": "Portland Trail Blazers", "years": "1999–2003"},
        ],
        "position": "F",
        "career_points": 18940,
        "career_rebounds": 7494,
        "career_assists": 6135,
        "championships": {"count": 6, "years": ['1991', '1992', '1993', '1996', '1997', '1998']},
        "mvp": {"count": 0, "years": []},
        "finals_mvp": {"count": 0, "years": []},
        "all_star_selections": 7,
        "all_nba_selections": 7,
        "hof_year": 2010,
    },
    "Shaquille O'Neal": {
        "teams": [
            {"team": "Orlando Magic", "years": "1992–1996"},
            {"team": "Los Angeles Lakers", "years": "1996–2004"},
            {"team": "Miami Heat", "years": "2004–2008"},
            {"team": "Phoenix Suns", "years": "2008–2009"},
            {"team": "Cleveland Cavaliers", "years": "2009–2010"},
            {"team": "Boston Celtics", "years": "2010–2011"},
        ],
        "position": "C",
        "career_points": 28596,
        "career_rebounds": 13099,
        "career_assists": 3026,
        "championships": {"count": 4, "years": ['2000', '2001', '2002', '2006']},
        "mvp": {"count": 1, "years": ['2000']},
        "finals_mvp": {"count": 3, "years": ['2000', '2001', '2002']},
        "all_star_selections": 15,
        "all_nba_selections": 14,
        "hof_year": 2016,
    },
    "Stephen Curry": {
        "teams": [
            {"team": "Golden State Warriors", "years": "2009–2024"},
        ],
        "position": "G",
        "career_points": 23668,
        "career_rebounds": 4509,
        "career_assists": 6119,
        "championships": {"count": 4, "years": ['2015', '2017', '2018', '2022']},
        "mvp": {"count": 2, "years": ['2015', '2016']},
        "finals_mvp": {"count": 1, "years": ['2022']},
        "all_star_selections": 10,
        "all_nba_selections": 10,
        "hof_year": None,
    },
    "Steve Nash": {
        "teams": [
            {"team": "Phoenix Suns", "years": "1996–1998, 2004–2012"},
            {"team": "Dallas Mavericks", "years": "1998–2004"},
            {"team": "Los Angeles Lakers", "years": "2012–2015"},
        ],
        "position": "G",
        "career_points": 17387,
        "career_rebounds": 3642,
        "career_assists": 10335,
        "championships": {"count": 0, "years": []},
        "mvp": {"count": 2, "years": ['2005', '2006']},
        "finals_mvp": {"count": 0, "years": []},
        "all_star_selections": 8,
        "all_nba_selections": 7,
        "hof_year": 2018,
    },
    "Tim Duncan": {
        "teams": [
            {"team": "San Antonio Spurs", "years": "1997–2016"},
        ],
        "position": "F/C",
        "career_points": 26496,
        "career_rebounds": 15091,
        "career_assists": 4225,
        "championships": {"count": 5, "years": ['1999', '2003', '2005', '2007', '2014']},
        "mvp": {"count": 2, "years": ['2002', '2003']},
        "finals_mvp": {"count": 3, "years": ['1999', '2003', '2005']},
        "all_star_selections": 15,
        "all_nba_selections": 15,
        "hof_year": 2020,
    },
    "Walt Frazier": {
        "teams": [
            {"team": "New York Knicks", "years": "1967–1977"},
            {"team": "Cleveland Cavaliers", "years": "1977–1979"},
        ],
        "position": "G",
        "career_points": 15581,
        "career_rebounds": 4830,
        "career_assists": 5040,
        "championships": {"count": 2, "years": ['1970', '1973']},
        "mvp": {"count": 0, "years": []},
        "finals_mvp": {"count": 0, "years": []},
        "all_star_selections": 7,
        "all_nba_selections": 6,
        "hof_year": 1987,
    },
    "Wes Unseld": {
        "teams": [
            {"team": "Baltimore / Capital / Washington Bullets", "years": "1968–1981"},
        ],
        "position": "C",
        "career_points": 10624,
        "career_rebounds": 13769,
        "career_assists": 3822,
        "championships": {"count": 1, "years": ['1978']},
        "mvp": {"count": 1, "years": ['1969']},
        "finals_mvp": {"count": 1, "years": ['1978']},
        "all_star_selections": 5,
        "all_nba_selections": 1,
        "hof_year": 1988,
    },
    "Willis Reed": {
        "teams": [
            {"team": "New York Knicks", "years": "1964–1974"},
        ],
        "position": "C/F",
        "career_points": 12183,
        "career_rebounds": 8414,
        "career_assists": 1186,
        "championships": {"count": 2, "years": ['1970', '1973']},
        "mvp": {"count": 1, "years": ['1970']},
        "finals_mvp": {"count": 2, "years": ['1970', '1973']},
        "all_star_selections": 7,
        "all_nba_selections": 5,
        "hof_year": 1982,
    },
    "Wilt Chamberlain": {
        "teams": [
            {"team": "Philadelphia / San Francisco Warriors", "years": "1959–1965"},
            {"team": "Philadelphia 76ers", "years": "1965–1968"},
            {"team": "Los Angeles Lakers", "years": "1968–1973"},
        ],
        "position": "C",
        "career_points": 31419,
        "career_rebounds": 23924,
        "career_assists": 4643,
        "championships": {"count": 2, "years": ['1967', '1972']},
        "mvp": {"count": 4, "years": ['1960', '1966', '1967', '1968']},
        "finals_mvp": {"count": 1, "years": ['1972']},
        "all_star_selections": 13,
        "all_nba_selections": 10,
        "hof_year": 1979,
    },
}